# Generated by Django 4.2.3 on 2023-11-18 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_user_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='model',
            new_name='date',
        ),
    ]
